spring:
    application:
        name: resource-server  
    datasource: 
        driverClassName: com.mysql.jdbc.Driver
        url: "jdbc:mysql://localhost:3306/userservice2fa?autoreconnect=true"
        password: "abc1234"
        username: "root"
        testOnBorrow: true
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 30000
        validationQuery: SELECT 1
        max-active: 15
        max-idle: 10
        max-wait: 8000
server:
  port: 8096
security:
    oauth2:
      resource:
        jwt:
          key-value: -----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAifHI/pIpvbdJYzqFPIpyp6RoUF4cTiBbMx2qijmEL+R7WalKpTeo+IRXMtfdDFirGpFw+m+0r6rW8rnizJ1V05c+ItamrfS0bHdYXUdI05JIHdX3pFWCg8hjjeECMoLvEEdYGON4WoM9RSVS+scV58qmBmAp1Vqm+XKaxAW+EXgXDqj6Jp9RDZEBsAppXWngB9gdYy9ZarAnt5hyEp/cNHJzgHviImt/CdEpJX0vmOp8heVoe1gbdCYLKFDGF/G/oNQSxhI92wZEJA5gdLhB9oFr5ZYyP646Qnle0L6KehOp15JMchsgePzpokgtGn4yYmpiCEiFqmwsUyH8BWImLQIDAQAB-----END PUBLIC KEY-----