spring:
    application:
        name: resource-server  
    datasource: 
        driverClassName: com.mysql.jdbc.Driver
        url: "jdbc:mysql://localhost:3306/userservice2fa?autoreconnect=true"
        password: "abc1234"
        username: "root"
        testOnBorrow: true
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 30000
        validationQuery: SELECT 1
        max-active: 15
        max-idle: 10
        max-wait: 8000
server:
  port: 8096
security:
    oauth2:
      resource:
        jwt:
          key-value: -----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArJs9DHCcsqevTqYR5Jp9tzNldaBqfTGW03NmUpsm7iylLDtX0RXbB/v+KxeRLGQg052DVnMAPCPYuH7aoyG28rYydE/4zZL7OnlTl5GUnDq9p5Sz0fokku0yYZh/mOlzjzOVXUZeMb9O563kHwHW/ebnYjIHakBrKa1j222UPz9qa36+d4jUwW5H4U5Lbe2RhT9KfQQiUYQQikVe7aRn45mo5aN8PkCQVz9m17SYDAwx+ZOnVq73OTAcRUO8vF1mtrYpwH4ge6ClUTPAo2KXCa4NtMswgC8Mrod8c/41jYi50gcem0sKTSFw7JA2aRzs7VgMPFbINVBFUb6sj+DZCQIDAQAB-----END PUBLIC KEY-----